/**
 * Backend permission catalogue and role–permission map.
 * Must stay in sync with src/lib/permissions.ts for API authorisation.
 */

const PERMISSIONS = {
  SALE_CREATE: 'sale.create',
  REFUND_REQUEST: 'refund.request',
  REFUND_APPROVE: 'refund.approve',
  VOID_REQUEST: 'void.request',
  VOID_APPROVE: 'void.approve',
  DISCOUNT_APPLY_AUTO: 'discount.apply.auto',
  DISCOUNT_APPLY_MANUAL: 'discount.apply.manual',
  DISCOUNT_APPROVE: 'discount.approve',
  PROMO_MANAGE: 'promo.manage',
  CASH_DRAWER_OPEN: 'cash.drawer.open',
  CASH_DRAWER_CLOSE: 'cash.drawer.close',
  CASH_DRAWER_REVIEW: 'cash.drawer.review',
  CASH_PAYOUT: 'cash.payout',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_RECEIVE: 'inventory.receive',
  INVENTORY_RECEIVE_POST: 'inventory.receive.post',
  INVENTORY_RECEIVE_APPROVE: 'inventory.receive.approve',
  INVENTORY_COUNT: 'inventory.count',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_ADJUST_APPROVE: 'inventory.adjust.approve',
  INVENTORY_TRANSFER: 'inventory.transfer',
  PURCHASING_PO_CREATE: 'purchasing.po.create',
  PURCHASING_PO_APPROVE: 'purchasing.po.approve',
  PURCHASING_PO_SEND: 'purchasing.po.send',
  PURCHASING_INVOICE_MATCH: 'purchasing.invoice.match',
  PURCHASING_VIEW: 'purchasing.view',
  REPORT_VIEW: 'report.view',
  REPORT_VIEW_OWN_SHIFT: 'report.view.own_shift',
  REPORT_EXPORT: 'report.export',
  AUDIT_VIEW: 'audit.view',
  DISCREPANCY_VIEW: 'discrepancy.view',
  DISCREPANCY_RESOLVE: 'discrepancy.resolve',
  ADMIN_USERS: 'admin.users',
  ADMIN_SETTINGS: 'admin.settings',
  ADMIN_DISCOUNT_RULES: 'admin.discount_rules',
  ADMIN_DEVICES: 'admin.devices',
  APPROVALS_VIEW: 'approvals.view',
  INCIDENT_CREATE: 'incident.create',
  INCIDENT_VIEW: 'incident.view',
  HOST_GUEST_LIST: 'host.guest_list',
  HOST_BOOKINGS: 'host.bookings',
};

const ROLE_PERMISSIONS = {
  owner: [
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.REFUND_APPROVE,
    PERMISSIONS.VOID_APPROVE,
    PERMISSIONS.DISCOUNT_APPLY_AUTO,
    PERMISSIONS.DISCOUNT_APPLY_MANUAL,
    PERMISSIONS.DISCOUNT_APPROVE,
    PERMISSIONS.PROMO_MANAGE,
    PERMISSIONS.CASH_DRAWER_OPEN,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.CASH_DRAWER_REVIEW,
    PERMISSIONS.CASH_PAYOUT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_RECEIVE_POST,
    PERMISSIONS.INVENTORY_RECEIVE_APPROVE,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_ADJUST_APPROVE,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_PO_CREATE,
    PERMISSIONS.PURCHASING_PO_APPROVE,
    PERMISSIONS.PURCHASING_PO_SEND,
    PERMISSIONS.PURCHASING_INVOICE_MATCH,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DISCREPANCY_VIEW,
    PERMISSIONS.DISCREPANCY_RESOLVE,
    PERMISSIONS.ADMIN_USERS,
    PERMISSIONS.ADMIN_SETTINGS,
    PERMISSIONS.ADMIN_DISCOUNT_RULES,
    PERMISSIONS.ADMIN_DEVICES,
    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
  ],
  general_manager: [
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.REFUND_APPROVE,
    PERMISSIONS.VOID_APPROVE,
    PERMISSIONS.DISCOUNT_APPLY_AUTO,
    PERMISSIONS.DISCOUNT_APPLY_MANUAL,
    PERMISSIONS.DISCOUNT_APPROVE,
    PERMISSIONS.PROMO_MANAGE,
    PERMISSIONS.CASH_DRAWER_OPEN,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.CASH_DRAWER_REVIEW,
    PERMISSIONS.CASH_PAYOUT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_RECEIVE_POST,
    PERMISSIONS.INVENTORY_RECEIVE_APPROVE,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_ADJUST_APPROVE,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_PO_CREATE,
    PERMISSIONS.PURCHASING_PO_APPROVE,
    PERMISSIONS.PURCHASING_PO_SEND,
    PERMISSIONS.PURCHASING_INVOICE_MATCH,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DISCREPANCY_VIEW,
    PERMISSIONS.DISCREPANCY_RESOLVE,
    PERMISSIONS.ADMIN_SETTINGS,
    PERMISSIONS.ADMIN_DISCOUNT_RULES,
    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
  ],
  senior_manager: [
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.REFUND_APPROVE,
    PERMISSIONS.VOID_APPROVE,
    PERMISSIONS.DISCOUNT_APPLY_AUTO,
    PERMISSIONS.DISCOUNT_APPLY_MANUAL,
    PERMISSIONS.DISCOUNT_APPROVE,
    PERMISSIONS.PROMO_MANAGE,
    PERMISSIONS.CASH_DRAWER_OPEN,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.CASH_DRAWER_REVIEW,
    PERMISSIONS.CASH_PAYOUT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_RECEIVE_POST,
    PERMISSIONS.INVENTORY_RECEIVE_APPROVE,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_ADJUST_APPROVE,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_PO_CREATE,
    PERMISSIONS.PURCHASING_PO_SEND,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DISCREPANCY_VIEW,
    PERMISSIONS.DISCREPANCY_RESOLVE,
    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
  ],
  manager: [
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.REFUND_APPROVE,
    PERMISSIONS.VOID_APPROVE,
    PERMISSIONS.DISCOUNT_APPLY_AUTO,
    PERMISSIONS.DISCOUNT_APPLY_MANUAL,
    PERMISSIONS.DISCOUNT_APPROVE,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.CASH_DRAWER_REVIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DISCREPANCY_VIEW,
    PERMISSIONS.APPROVALS_VIEW,
    PERMISSIONS.INCIDENT_VIEW,
  ],
  cashier: [
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.REFUND_REQUEST,
    PERMISSIONS.VOID_REQUEST,
    PERMISSIONS.DISCOUNT_APPLY_AUTO,
    PERMISSIONS.CASH_DRAWER_OPEN,
    PERMISSIONS.CASH_DRAWER_CLOSE,
    PERMISSIONS.REPORT_VIEW_OWN_SHIFT,
  ],
  stock_clerk: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_RECEIVE_POST,
    PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_PO_CREATE,
    PERMISSIONS.DISCREPANCY_VIEW,
  ],
  host: [
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.HOST_GUEST_LIST,
    PERMISSIONS.HOST_BOOKINGS,
    PERMISSIONS.REPORT_VIEW_OWN_SHIFT,
  ],
  security: [
    PERMISSIONS.INCIDENT_CREATE,
    PERMISSIONS.INCIDENT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],
  accountant: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PURCHASING_VIEW,
    PERMISSIONS.PURCHASING_INVOICE_MATCH,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DISCREPANCY_VIEW,
  ],
};

function getPermissions(role) {
  const list = ROLE_PERMISSIONS[role];
  return new Set(list ?? []);
}

function hasPermission(role, permission) {
  if (!role || !permission) return false;
  return getPermissions(role).has(permission);
}

/**
 * Express middleware factory: require authenticated user and given permission.
 * Expects req.user = { id, role } (set by auth middleware).
 */
function requirePermission(permission) {
  return (req, res, next) => {
    if (!req.user) {
      return res.status(401).json({ error: 'Authentication required' });
    }
    if (!hasPermission(req.user.role, permission)) {
      return res.status(403).json({ error: 'Insufficient permissions' });
    }
    next();
  };
}

/**
 * Optional: require auth only (no specific permission). Use for endpoints that
 * need to know who is acting but allow any logged-in user.
 */
function requireAuth(req, res, next) {
  if (!req.user) {
    return res.status(401).json({ error: 'Authentication required' });
  }
  next();
}

export { PERMISSIONS, ROLE_PERMISSIONS, hasPermission, requirePermission, requireAuth };
